M48
; DRILL file KiCad 10.0.6 date 2026-10-07T19:37:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-07T19:37:18-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C6.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C7.000
%
G90
G05
T1
X150.0Y-26.25
X150.0Y-148.75
T2
X150.0Y-62.5
X150.0Y-77.5
X150.0Y-117.5
X150.0Y-132.5
T3
X150.0Y-42.5
X150.0Y-97.5
M30
